#!/bin/sh
version=$(cat /etc/freifunk_version)

cat > /etc/opkg.conf <<EOF 
# Note: Later sources overwrite earlier ones:
src/gz barrier_breaker_packages http://downloads.openwrt.org/barrier_breaker/14.07/ar71xx/generic/packages/packages
src/gz barrier_breaker_base http://downloads.openwrt.org/barrier_breaker/14.07/ar71xx/generic/packages/base
src/gz barrier_breaker_luci http://downloads.openwrt.org/barrier_breaker/14.07/ar71xx/generic/packages/luci
src/gz barrier_breaker_management http://downloads.openwrt.org/barrier_breaker/14.07/ar71xx/generic/packages/management
src/gz barrier_breaker_routing http://downloads.openwrt.org/barrier_breaker/14.07/ar71xx/generic/packages/routing
src/gz barrier_breaker_telephony http://downloads.openwrt.org/barrier_breaker/14.07/ar71xx/generic/packages/telephony

src/gz ff-kbu-v6 http://jenkins-v6.kbu.freifunk.net/files/packages/$version
EOF
cat /etc/opkg.conf.default >> /etc/opkg.conf
