#!/bin/sh

UPLOAD_URL=$1
KEY=`/etc/init.d/fastd show_key mesh_vpn`
CURLC=`which curl`
VERSION=$(cat /etc/freifunk_version)
MAC=$(uci get freifunk.@node[0].nodeid)
while [ 1 = 1 ]
do
        $CURLC "$UPLOAD_URL/upload_key?nodeid=${MAC}&_method=post&key=${KEY}&fw_version=${VERSION}" && break
        #$WGETC "$UPLOAD_URL/upload_key?nodeid=${MAC}&_method=post&key=${KEY}&fw_version=${VERSION}" -O - && break
	sleep 30
done
