#!/bin/sh
. /lib/freifunk/lib_node.sh
UPLOAD_URL=$1
MAC=${2//:/}
KEY=`/usr/sbin/fastd --machine-readable --show-key -c /tmp/fastd/secret.mesh_vpn.conf`
WGETC=`which wget`
VERSION=$(cat /etc/freifunk_version)
BOARD="$(get_board_name)"
while [ 1 = 1 ]
do
        $WGETC -q --post-data "board=${BOARD}&nodeid=${MAC}&key=${KEY}&fw_version=${VERSION}" $UPLOAD_URL -O - && break
	sleep 30
done
