#!/bin/sh

UPLOAD_URL=$1
MAC=${2//:/}
KEY=`/usr/sbin/fastd --machine-readable --show-key -c /tmp/fastd/secret.mesh_vpn.conf`
CURLC=`which curl`
VERSION=$(cat /etc/freifunk_version)

while [ 1 = 1 ]
do
        $CURLC -F nodeid=${MAC} -F key=${KEY} -F fw_version=${VERSION} $UPLOAD_URL -s && break
	sleep 30
done
