#!/bin/sh
. /lib/freifunk/lib_node.sh

uci set wireless.radio0.htmode='HT20'
uci set wireless.wifi_mesh.mcast_rate='12000'

if is_dual_wifi; then
uci set wireless.radio1.htmode='HT20'
uci set wireless.wifi_mesh5.mcast_rate='12000'

fi

uci commit wireless

/etc/init.d/network restart

