#!/bin/sh

. /lib/ar71xx.sh
. /lib/freifunk/lib_node.sh

local lan_ifname="$(uci get network.lan.ifname)"
local wan_ifname="$(uci get network.wan.ifname)"


local board="$(ar71xx_board_name)"
#port_info=$(swconfig dev eth0 help | grep -oe "cpu @ [0-9]")
#cpu_port=${port_info//cpu @/}

uci -q batch <<EOF
delete network.lan

set network.wan.type='bridge'
set network.wan.proto='dhcp'
set network.wan.accept_ra='0'
set network.wan.auto='1'

set network.freifunk='interface'
set network.freifunk.ifname='bat0'
set network.freifunk.type='bridge'
set network.freifunk.proto='none'
set network.freifunk.auto='1'
set network.freifunk.accept_ra='1'

set network.mesh='interface'
set network.mesh.proto='none'
set network.mesh.mtu='1528'

set network.freifunk.ifname='bat0'
set network.freifunk.dns='2001:67c:20a0:b102::1'


EOF

case "$board" in
tl-wr1043nd|\
tl-wdr3600|\
tl-wdr4300) # fix up duplicate mac addresses
	local oIFS="$IFS"; IFS=":"; set -- $(get_main_address); IFS="$oIFS"
	local b2mask=0x02

	local wanaddr=$(printf "%02x:%s:%s:%02x:%s:%02x" $(( 0x$1 | $b2mask )) $2 $3 $(( (0x$4 + 1) % 0x100 )) $5 $(( (0x$6 + 1) % 0x100 )) )

	uci set network.wan.macaddr="$wanaddr"
	;;
esac

uci set network.freifunk.macaddr=$(get_main_address)
uci commit network
