#!/bin/sh
. /lib/freifunk/lib_node.sh

dual_wifi=$(is_dual_wifi)

# If the device has to wifi, wifi 2 has to be set up as well ..
if($dual_wifi -eq 1);then
# Setting radio1.disabled='1' makes no sense to me ...

uci -q batch <<EOF

delete wireless.radio1.disabled
delete wireless.@wifi-iface[0]
set wireless.radio1.disabled='1'
EOF
fi


uci -q batch <<EOF
delete wireless.radio0.disabled
delete wireless.@wifi-iface[0]

set wireless.radio0.channel='1'
set wireless.radio0.htmode='HT40+'
set wireless.radio0.country='DE'

set wireless.wifi_freifunk='wifi-iface'
set wireless.wifi_freifunk.device='radio0'
set wireless.wifi_freifunk.network='freifunk'
set wireless.wifi_freifunk.mode='ap'
set wireless.wifi_freifunk.ssid='kbu.freifunk.net'

set wireless.wifi_mesh='wifi-iface'
set wireless.wifi_mesh.device='radio0'
set wireless.wifi_mesh.network='mesh'
set wireless.wifi_mesh.mode='adhoc'
set wireless.wifi_mesh.ssid='02:d1:11:37:fc:39'
set wireless.wifi_mesh.bssid='02:d1:11:37:fc:39'

commit wireless
EOF

