#!/bin/sh

#Include lib_node.sh for accessing node_id
. /lib/freifunk/lib_node.sh


# This script creates collectd.conf after flashing.

# collectd uses node_id.nodes.kbu.freifunk.net as hostname
# nodes.kbu.freifunk.net does not exists at this time (2012-01-15). 
#However, if needed, it can be set up using register / mysql- or ldap-based bind9 easily

local hostname="$(node_id).nodes.kbu.freifunk.net" 

cat > /etc/collectd <<EOF
Hostname   "${hostname}"
BaseDir     "/var/lib/collectd"
PIDFile     "/var/run/collectd.pid"
Interval    10
ReadThreads 2

LoadPlugin network
LoadPlugin interface
LoadPlugin netlink

<Plugin interface>
        Interface "br-wan"
        IgnoreSelected false
</Plugin>

<Plugin network>
        Server "collectd.kbu.freifunk.net" "25827"
</Plugin>
EOF
