#!/bin/sh



VERSION_FILE=/etc/freifunk_version

KEEP_VERSION_FILE=/etc/.freifunk_version_keep

UPGRADE_DIR=/lib/freifunk/upgrade


newer_than() {
	local old="$(printf '%s\n%s\n' "$1" "$2" | sort -n | head -n 1)"
	test "$1" != "$old"
}


do_dir() {
	local s
	for s in "$1"/*; do "$s"; done
}


version="$(cat "$VERSION_FILE")"

oldversion="$(cat "$KEEP_VERSION_FILE" 2>/dev/null)"


(
	cd "$UPGRADE_DIR"

	if [ -z "$oldversion" ]; then
		do_dir initial
	else
		local v

		for v in *; do
			if [ "$v" = initial ]; then continue; fi

			if newer_than "$v" "$oldversion"; then
				do_dir "$v"
			fi
		done
	fi
)

echo "$version" > "$KEEP_VERSION_FILE"

