#!/bin/sh



VERSION_FILE=/etc/freifunk_version

KEEP_VERSION_FILE=/etc/.freifunk_version_keep

UPGRADE_DIR=/lib/freifunk/upgrade

newer_than() {
	local old="$(printf '%s\n%s\n' "$1" "$2" | sort -n | head -n 1)"
	test "$1" != "$old"
}


do_dir() {
	local s
	for s in "$1"/*; do 
		echo "$(date): executing $s" >> /etc/.upgrade-log.txt
		"$s >> /etc/.upgrade-log.txt 2>> /etc/.upgrade-log.txt"; 
	done
}


version="$(cat "$VERSION_FILE")"

oldversion="$(cat "$KEEP_VERSION_FILE" 2>/dev/null)"
echo "$(date): Upgrading from $oldversion to $version" >> /etc/.upgrade-log.txt

(
	cd "$UPGRADE_DIR"

	if [ -z "$oldversion" ]; then
# Set initial configuration:
		do_dir initial
	else
		local v

		for v in *; do
			if [ "$v" = initial ]; then continue; fi

			if newer_than "$v" "$oldversion"; then
                                echo "$(date): Executing upgrade scripts at: $v" >> /etc/.upgrade-log.txt
				do_dir "$v"
			fi
		done
	fi
)

echo "$version" > "$KEEP_VERSION_FILE"

