#!/bin/sh

cat > /etc/collectd.conf << EOF
BaseDir "/var/run/collectd"
Include "/etc/collectd/conf.d"
PIDFile "/var/run/collectd.pid"
PluginDir "/usr/lib/collectd"
TypesDB "/usr/share/collectd/types.db"
Interval 30
ReadThreads 2

LoadPlugin rrdtool
<Plugin rrdtool>
	DataDir "/tmp/rrd"
	RRARows 100
	RRASingle true
	RRATimespan 3600
	RRATimespan 86400
	RRATimespan 604800
	RRATimespan 2678400
	RRATimespan 31622400
</Plugin>

LoadPlugin iwinfo
<Plugin iwinfo>
	IgnoreSelected true
	Interface bat0
	Interface "br-freifunk"
	Interface "br-wan"
	Interface eth0
	Interface "eth0.1"
	Interface "eth0.2"
	Interface "mesh-vpn"
</Plugin>

LoadPlugin interface
<Plugin interface>
	IgnoreSelected true
	Interface lo
</Plugin>

LoadPlugin ping
<Plugin ping>
	TTL 127
	Interval 30
	Host "fdd3:5d16:b5dd:2::1"
</Plugin>

LoadPlugin network
<Plugin network>
	Server "fdd3:5d16:b5dd:2::1" "25827"
	Forward false
</Plugin>
EOF

uci set fastd.mesh_vpn.syslog_level=verbose
uci set fastd.mesh_vpn.method="salsa2012+gmac null"

cat > /etc/config/batman-adv << EOF
config 'mesh' 'bat0'
	option 'aggregated_ogms'
	option 'ap_isolation'
	option 'bonding'
	option 'fragmentation'
	option 'gw_bandwidth'
	option 'gw_mode' 'client'
	option 'gw_sel_class' '3'
	option 'log_level'
	option 'orig_interval' '5000'
	option 'vis_mode'
	option 'bridge_loop_avoidance' '1'
EOF
